version: "3.5"
services:
  REU-2023:
    ports: 
      - 8560
    container_name: REU-2023
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    stdin_open: true
    tty: true

volumes: 
  brondb_data_container:
  brondb_apps_data_container:

secrets:
  arango_root_password:
    file: /home/aurora/BRON/arango_root_password

